# Website settings
title: Dpad
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Dhruvesh Patel.
baseurl:  ""
url: "http://dhruveshp.com"
author:  # change following line to your infomation.
  name: Dhruvesh  # Be used at blog posts' author.
  first_name: Dhruvesh  # Be used at index page about me section.
  last_name: Patel  # Be used at index page about me section.
  avatar: /static/assets/img/landing/dp.jpg  # upload your avatar at directory and edit it.
  github_username: dhruvdcoder  # Leave blank if you don't have now
  linkedin_id: dhruveshp # Leave blank if you don't have now
  quora_id: Dhruvesh-Patel
  researchgate_id: Dhruvesh_Patel3
  goodreads_username: dhruvdreader
  facebook_username: dhruvdplayer  # Leave blank if you don't have now
  twitter_username: _dhruveshp  # Leave blank if you don't have now
  email: dhruveshp.forall@gmail.com  # Leave blank if you don't have now
  cv: "https://drive.google.com/file/d/1Z8u4_wnQiLDkyiV361f-kGfxHpb6NQCE/view"   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - icon: aws
      name: fa-aws
      source: font-awesome
    - icon: linux
      name: fa-linux
      source: font-awesome
    - icon: nginx
      name: devicon-nginx-original
      source: devicon
    - icon: git
      name: icon-git
      source: mfizz
  skill_icon2:
    - icon: cplusplus
      name: icon-cplusplus
      source: mfizz
    - icon: mongodb
      name: icon-mongodb
      source: mfizz
    - icon: d3
      name: icon-d3
      source: mfizz
    - icon: python
      name: icon-python
      source: mfizz
    - icon: vim
      name: devicon-vim-plain
      source: devicon
    - icon: docker
      name: devicon-docker-plain
      source: devicon
  desc: "Software engineer and a curious soul—that is me. You've reached my website which I use as a journal; as a bulletin board for my ideas and as a placeholder for myself in this enormous space that is internet. I talk about all things that I find interesting: Linux's ELF binaries, machine learning, software libraries, mathematics, etc. I come from an interdisciplinary background involving Robotics, Software Engineering, Machine Learning and Data Science. For a year, I was developing a set of Machine Learning (ML) and Natural Language Processing (NLP) based products at a nascent startup—-Kenome. Currently, I am pursuing my master's degree in Computer Science at UMass. Through 2+ years of experience in developing software and end-to-end machine learning pipelines, I have bolstered my understanding of the fundamentals of computer science with practical knowledge. I now am looking for bigger challenges on the unexplored frontiers of NLP and ML."

#other pages
include: ["_pages"]

# comment
disqus: 
  name: dhruveshp

# analytics
## google analytics
ga:
  id: UA-115661902-2

## google optimize
#go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
#index_carousel: on  # index page carousel switch
#blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rogue
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue

plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_inline_highlight
