# Website settings
title: Dpad
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Dhruvesh Patel.
#keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
#baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
#url: https://jarrekk.github.io/Jalpc  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
baseurl:  ""
url: "https://dhruvdcoder.github.io"
#img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before
img_path: /assets
# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Dhruvesh  # Be used at blog posts' author.
  first_name: Dhruvesh  # Be used at index page about me section.
  last_name: Patel  # Be used at index page about me section.
  avatar: /static/assets/img/landing/dp.jpg  # upload your avatar at directory and edit it.
  github_username: dhruvdcoder  # Leave blank if you don't have now
  linkedin_id: dhruveshp # Leave blank if you don't have now
  quora_id: Dhruvesh-Patel
  researchgate_id: Dhruvesh_Patel3
  goodreads_username: dhruvdreader
  facebook_username: dhruvdplayer  # Leave blank if you don't have now
  twitter_username: dhruvdplayer  # Leave blank if you don't have now
  email: dhruvdplayer@gmail.com  # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - icon: aws
      name: fa-aws
      source: font-awesome
    - icon: linux
      name: fa-linux
      source: font-awesome
    - icon: nginx
      name: devicon-nginx-original
      source: devicon
    - icon: git
      name: icon-git
      source: mfizz
  skill_icon2:
    - icon: cplusplus
      name: icon-cplusplus
      source: mfizz
    - icon: mongodb
      name: icon-mongodb
      source: mfizz
    - icon: d3
      name: icon-d3
      source: mfizz
    - icon: python
      name: icon-python
      source: mfizz
    - icon: vim
      name: devicon-vim-plain
      source: devicon
    - icon: docker
      name: devicon-docker-plain
      source: devicon
  desc: I am a software engineer and you've reached my lab where you'd find facts about me; some of my ideas and results of my random musings. I talk about all things that I find interesting; linux's elf binaries, machine learning; software libraries; mathematics and even Godel's incompleteness theorems.

#other pages
include: ["_pages"]

# comment
disqus: 
  name: dpad-1

# analytics
## google analytics
ga:
  id: UA-115661902-1

## google optimize
#go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
#index_carousel: on  # index page carousel switch
#blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rogue
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue

plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_inline_highlight
